### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by fearphage** [kz8s/tack#135]
I'm just curious if this is still in active development. 

Is there anywhere to talk to devs/maintainers? I tried gitter, but I posted the previous message was from November 2016.

**Comment by yagonobre** [comment]
Yes, it is active

If u want to talk with me nobre.yago@gmail.com

**Comment by nkhine** [comment]
hi, any updates on this project, specifically the merge of https://github.com/kz8s/tack/pull/127

**Comment by yagonobre** [comment]
@wellsie

**Comment by wellsie** [comment]
@yagonobre @fearphage

hi. sorry for the delayed response. yes definitely still active. updated a bunch of things today:

- terraform 0.93
- etcd3
- TLS for *all* etcd communications
- k8s 1.6.2
- private-to-cluster certificate authority within cluster
- dashboard 1.6.0
- fixed terraform warnings

@nkhine - sorry about #127; it won't work now that TLS certificate generation has been moved to inside the cluster. tbh i haven't been using the bastion for accessing etcd. do you use it for that purpose?

**Comment by rimusz** [comment]
@wellsie hmm, I still see `etcd2.service` in bastion and worker cloud-configs

**Comment by wellsie** [comment]
@rimusz - thanks for pointing out that cruft. etcdctl on bastion:

```
$ make ssh-bastion
$ etcdctl cluster-health
```
