### ISSUE TITLE
SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)

### ISSUE THREAD

**Issue by wellsie** [kz8s/tack#18]
```
Jun 02 15:03:56 ip-10-0-0-10.us-west-1.compute.internal kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
```

related:
- https://github.com/docker/docker/issues/20798
- https://github.com/docker/docker/issues/20871
- https://github.com/docker/docker/issues/7952

**Comment by streamnsight** [comment]
same here.

**Comment by wellsie** [comment]
just verified this issue is resolved on CoreOS alpha (1122.0.0)

**Comment by alogoc** [comment]
Doesn't look like it's solved. I first experienced this issue after upgrading to 1122.2.0 stable.

```
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   1f8f545
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   1f8f545
 Built:
 OS/Arch:      linux/amd64
```

```
dmesg | grep -i "SELinux: mount invalid" | wc -l
574
```

**Comment by neith00** [comment]
I also face the same issue:
dmesg | grep -i "SELinux: mount invalid" |wc -l
538

I0303 09:09:50.523138 11271 update_engine_client.cc:237] Querying Update Engine status...
LAST_CHECKED_TIME=1487863023
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATED_NEED_REBOOT
NEW_VERSION=1235.12.0
NEW_SIZE=264591106

Docker version 1.12.6, build d5236f0

**Comment by wellsie** [comment]
https://github.com/coreos/bugs/issues/1580

**Comment by cemo** [comment]
@wellsie is this issue causing issues persistent storages on k8s? I saw these errors on our cluster and have no idea to how to solve it.

**Comment by wellsie** [comment]
These are upstream issues. No data loss afaict

**Comment by cemo** [comment]
when I try to mount EBS with `persistentvolumeclaim`, volumes could not be mount. I see that volumes are stucked on AWS console. I thought this is related to this issue since some people are also stated problems about EBS mounting. Do you think that this can can cause issues about mounting?

**Comment by wellsie** [comment]
Are you using the latest bits from master ?

**Comment by cemo** [comment]
No.

![image](https://cloud.githubusercontent.com/assets/44156/25620157/210fe882-2f56-11e7-8032-79dd0b1bfcbf.png)

**Comment by cemo** [comment]
@wellsie my issue resolved when I used ebs `st1` instead of `gp2`. I am not sure what was the root cause but hope that it will help someone else too.
